include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-nfttl
LUCI_TITLE:=LuCI Support for TTL Settings via nftables
LUCI_DEPENDS:=+nftables
PKG_MAINTAINER:=DotyTheCat <support@dotycat.com>

include ../../luci.mk

